service:
  name: zwe-aws-tests

plugins:
    - serverless-webpack
    - serverless-plugin-export-endpoints

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  test-request-response:
    handler: test/handler.reqres
    events:
      - http:
          method: post
          path: testReqRes/{param1}/{param2}
          request:
            parameters:
              paths:
                param1: true
                param2: false
